### ISSUE TITLE
Dropbox new OAuth2 (with supporting refresh token).

### ISSUE THREAD

**Issue by mala-karta** [stevenmaguire/oauth2-dropbox#11]
Hi! Dropbox plans do not support long-live access token (after September 2021) and will support refresh token. Will you change this lib according to new rules?

More info is here: [https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens](https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens)

**Comment by Mataniko** [comment]
The lib already works as is with refresh tokens, all you need to do is not to set a `redirectUri` when setting up the provider.

**Comment by mala-karta** [comment]
Thank you!
